# PyTorch 101: Basic Tensor Operations
Welcome to PyTorch 101! In this notebook, we’ll explore PyTorch's basic tensor operations, similar to what you might already know from using NumPy. By the end of this tutorial, you’ll have a strong foundation in working with tensors in PyTorch, which is essential for any deep learning task.

## 1. Setting Up and Importing Libraries
To get started, run the cell below to import PyTorch. We’ll also use Matplotlib to visualize data.

In [1]:
# Import necessary libraries
!pip install torch torchvision torchaudio
import torch
import numpy as np
import matplotlib.pyplot as plt

# Check if PyTorch is installed correctly
print("PyTorch version:", torch.__version__)
print("Is CUDA available?", torch.cuda.is_available())

   ---------------------------------------- 0.0/203.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/203.1 MB 653.6 kB/s eta 0:05:11
   ---------------------------------------- 0.1/203.1 MB 1.4 MB/s eta 0:02:21
   ---------------------------------------- 0.3/203.1 MB 1.7 MB/s eta 0:01:57
   ---------------------------------------- 0.5/203.1 MB 2.4 MB/s eta 0:01:27
   ---------------------------------------- 0.8/203.1 MB 3.2 MB/s eta 0:01:04
   ---------------------------------------- 1.4/203.1 MB 4.8 MB/s eta 0:00:43
   ---------------------------------------- 2.3/203.1 MB 7.0 MB/s eta 0:00:29
    --------------------------------------- 4.2/203.1 MB 11.3 MB/s eta 0:00:18
   - -------------------------------------- 6.7/203.1 MB 15.8 MB/s eta 0:00:13
   - -------------------------------------- 9.8/203.1 MB 20.8 MB/s eta 0:00:10
   -- ------------------------------------- 12.5/203.1 MB 54.4 MB/s eta 0:00:04
   --- ------------------------------------ 15.9/203.1 MB 65.6 M

## 2. Creating Tensors
Tensors are the core data structure in PyTorch. Think of them as multi-dimensional arrays, similar to NumPy arrays.

### Example: Creating Tensors from Lists or NumPy Arrays

In [2]:
# Create a tensor from a list
tensor_from_list = torch.tensor([1, 2, 3, 4])
print("Tensor from list:", tensor_from_list)

# Create a tensor from a NumPy array
np_array = np.array([5, 6, 7, 8])
tensor_from_np = torch.tensor(np_array)
print("Tensor from numpy array:", tensor_from_np)

Tensor from list: tensor([1, 2, 3, 4])
Tensor from numpy array: tensor([5, 6, 7, 8], dtype=torch.int32)


### Exercise 1: Create a 2x3 tensor with the numbers 1 through 6.

In [3]:
# Your code here
my_tensor = torch.tensor(([1,2,3],[4,5,6]))
print("2x3 tensor:\n", my_tensor)

2x3 tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])


## 3. Tensor Types and Attributes
Each tensor has attributes such as `dtype`, `shape`, and `device`. Understanding these attributes is crucial for managing tensors.

In [4]:
# Example tensor
example_tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

print("Data type:", example_tensor.dtype)
print("Shape:", example_tensor.shape)
print("Device:", example_tensor.device)

Data type: torch.float32
Shape: torch.Size([2, 2])
Device: cpu


### Exercise 2: Create a 3x3 float tensor with all values set to 0.0, then check its attributes.

In [23]:
# Your code here
zero_tensor = torch.zeros([3,3])
print("3x3 tensor:\n", zero_tensor)
print("Data type:", zero_tensor.dtype)
print("Shape:", zero_tensor.shape)

3x3 tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Data type: torch.float32
Shape: torch.Size([3, 3])


## 4. Basic Tensor Operations
Just like in NumPy, you can perform mathematical operations on tensors.

### Example: Basic Arithmetic Operations

In [24]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: tensor([5, 7, 9])
Subtraction: tensor([-3, -3, -3])
Multiplication: tensor([ 4, 10, 18])
Division: tensor([0.2500, 0.4000, 0.5000])


### Exercise 3: Create two 3x3 tensors and perform element-wise addition, subtraction, and multiplication.

In [25]:
# Your code here
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_b = torch.tensor([[6, 5, 4], [3, 2, 1]])

# Perform operations
print("Addition:\n", tensor_a + tensor_b)
print("Subtraction:\n", tensor_a - tensor_b)
print("Multiplication:\n", tensor_a * tensor_b)

Addition:
 tensor([[7, 7, 7],
        [7, 7, 7]])
Subtraction:
 tensor([[-5, -3, -1],
        [ 1,  3,  5]])
Multiplication:
 tensor([[ 6, 10, 12],
        [12, 10,  6]])


## 5. Matrix Multiplication
Matrix multiplication is essential in neural networks. PyTorch provides several ways to perform it.

In [26]:
# 2x3 tensor
matrix_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
# 3x2 tensor
matrix_b = torch.tensor([[7, 8], [9, 10], [11, 12]])

result = torch.matmul(matrix_a, matrix_b)
print("Matrix multiplication result:\n", result)

Matrix multiplication result:
 tensor([[ 58,  64],
        [139, 154]])


### Exercise 4: Create a 2x3 and a 3x2 tensor, then perform matrix multiplication.

In [33]:
# Your code here
matrix_a = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Shape: 2x3
matrix_b = torch.tensor([[7, 8], [9, 10], [11, 12]])  # Shape: 3x2

# Perform matrix multiplication
result = torch.matmul(matrix_a, matrix_b)
print("Matrix multiplication result:\n", result)

Matrix multiplication result:
 tensor([[ 58,  64],
        [139, 154]])


## 6. Tensor Reshaping
Reshaping tensors is helpful for feeding data into neural networks, where data often needs to be resized.

In [32]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
reshaped = tensor.view(3, 2)  # Change shape to 3x2
print("Original tensor:\n", tensor)
print("Reshaped tensor:\n", reshaped)

Original tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Reshaped tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


### Exercise 5: Create a 1x6 tensor and reshape it into a 2x3 tensor.

In [31]:
# Your code here
tensor = torch.tensor([1,2,3,4,5,6])
reshaped_tensor = tensor.view(2,3)
print("Reshaped tensor:\n", reshaped_tensor)

Reshaped tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])


## Summary
In this notebook, you’ve explored the basics of PyTorch tensors, including creation, basic operations, matrix multiplication, and reshaping. Mastering these fundamentals will prepare you well for working with PyTorch in deep learning tasks. Keep experimenting and testing your understanding!